services:

  frontend:

    build:
      context: ./frontend

    container_name: event-frontend

    ports:
      - "80:80"

    depends_on:
      - backend


  backend:

    build:
      context: ./backend

    container_name: event-backend

    ports:
      - "5000:5000"

    environment:

      DB_HOST: mysql

      DB_USER: eventuser

      DB_PASSWORD: eventpass

      DB_NAME: eventdb

    depends_on:
      - mysql


  mysql:

    image: mysql:8.0

    container_name: event-mysql

    environment:

      MYSQL_ROOT_PASSWORD: rootpass

      MYSQL_DATABASE: eventdb

      MYSQL_USER: eventuser

      MYSQL_PASSWORD: eventpass

    ports:
      - "3306:3306"

    volumes:

      - mysql_data:/var/lib/mysql

      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


  prometheus:

    image: prom/prometheus

    container_name: prometheus

    ports:

      - "9090:9090"

    volumes:

      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml


volumes:

  mysql_data:
